apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.8.0
    replicas: 1  # Single-node cluster
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: secure
        port: 9093
        type: internal
        tls: true
    config:
      auto.create.topics.enable: false  # Disable automatic topic creation
      log.message.format.version: '3.8'  # Message format version
      offsets.topic.replication.factor: 1  # Replication factor for offsets topic
      ssl.cipher.suites: >-
        TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,
        TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_AES_256_GCM_SHA384
      ssl.enabled.protocols: 'TLSv1.3, TLSv1.2'
      ssl.protocol: TLSv1.3
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    resources:
      requests:
        cpu: 500m  # Lower CPU request
        memory: 1Gi  # Lower memory request
      limits:
        cpu: 1000m
        memory: 2Gi
      storage:
        type: ephemeral
  zookeeper:
    replicas: 1  # Single-node Zookeeper
    storage:
      type: ephemeral  # Add required storage configuration
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
      storage:
        type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
